services:
    nginx:
        build:
            context: docker/dev/nginx
        ports:
            -   "80:80"
        volumes:
            -   ./:/app
        depends_on:
            -   php-fpm

    php-fpm:
        build:
            context: docker/dev/php-fpm
        volumes:
            -   ./:/app

    php-cli:
        build:
            context: docker/dev/php-cli
        volumes:
            -   ./:/app
